### ISSUE TITLE
Comment is ignored

### ISSUE THREAD

**Issue by ShlomiD83** [favonia/cloudflare-ddns#1004]
Hi @favonia 
Hope you're doing well. 
I noticed that the comment I've set in my compose file isn't showing up on the A record on Cloudflare. 
Can you please check?

Many thanks. 

P.S if you have paypal i would like to by you a beer....

**Comment by favonia** [comment]
@ShlomiD83 In the past, I decided not to overwrite any mismatched parameters (except for IP addresses, of course). However, you should receive a message like this:
```
The updater will not overwrite proxy statuses, TTLs, or record comments.  You can change them in your Cloudflare dashboard at https://dash.cloudflare.com.
```
I'm curious if you've seen this message. On the other hand, you're not alone in mentioning this. I'm wondering if I should revisit my design decision and/or show the message more frequently. Looking forward to your feedback.

PS: Thank you for your support. I am reasonably well-paid by my day job with good benefits. Perhaps there are other open-source developers who need your support more. :slightly_smiling_face:

**Comment by ShlomiD83** [comment]
Haven't seen this message because I'm using quite mode. 
So I can remove the comment variable from my compose file safely..

**Comment by favonia** [comment]
@ShlomiD83 Ah, that's right. Maybe I should make it a warning so that it will display even in the quiet mode :thinking: Do you think that would help?

I recommend keeping the comment variable, just in case the updater has to recreate records. (This should be extremely unlikely, though, but who knows...).

**Comment by ShlomiD83** [comment]
> @ShlomiD83 Ah, that's right. Maybe I should make it a warning so that it will display even in the quiet mode 🤔 Do you think that would help?
> 
> I recommend keeping the comment variable, just in case the updater has to recreate records. (This should be extremely unlikely, though, but who knows...).

A warning could be a good idea.

**Comment by favonia** [comment]
@ShlomiD83 Do you have any preference between "actively overwriting things" and "warning about mismatches" (the current behavior)?

**Comment by ShlomiD83** [comment]
> @ShlomiD83 Do you have any preference between "actively overwriting things" and "warning about mismatches" (the current behavior)?

Whatever you think will be better.

**Comment by favonia** [comment]
Thanks. I will close this issue and continue the work in #1005.
