### ISSUE TITLE
Getting Error in logs, but update working fine, any reason behind this?

### ISSUE THREAD

**Issue by iAmSaugata** [favonia/cloudflare-ddns#147]
I am getting following error while it is trying to update the IP address, but in CF, ip getting updated successfully.

🌐 Detected the IPv4 address: X.X.X.X
😞 Failed to update a stale A record of "home.domain.fqdn" (ID: 294fcde3fbf00433d8c36b6cf47125d9): operation aborted during backoff: context deadline exceeded
😞 Failed to delete a stale A record of "home.domain.fqdn" (ID: 294fcde3fbf00433d8c36b6cf47125d9): operation aborted during backoff: context deadline exceeded
😞 Failed to add a new A record of "home.domain.fqdn": operation aborted during backoff: context deadline exceeded
😞 Failed to (fully) update A records of "home.domain.fqdn"
😞 Failed to retrieve records of "domain.fqdn": operation aborted during backoff: context deadline exceeded
😞 Failed to (fully) update A records of "domain.fqdn"
😞 Failed to send HTTP(S) request to "https://[2606:4700:4700::1111]/cdn-cgi/trace": Get "https://[2606:4700:4700::1111]/cdn-cgi/trace": dial tcp [2606:4700:4700::1111]:443: connect: cannot assign requested address
😞 Failed to detect the IPv6 address

**Comment by favonia** [comment]
Thanks for the reporting. This means the tool (or the library `cloudflare-go`, more specifically) could not receive the HTTP response before the connection times out, but the Cloudflare server actually received the request and implemented it correctly.

The most relevant setting is `UPDATE_TIMEOUT` which by default is `30s` (30 seconds). I thought that would be sufficient. What's your setting of `UPDATE_TIMEOUT`? Does changing it into a different value (such as `5m` for 5 minutes) solve the problem? If so, I prefer keeping the current default values until the next major release, and for now you can set it into a bigger value to prevent timeouts. If changing it into a large value still does not solve the problem, it means there's a serious bug and I'd like to fix it. Please let me know!

**Comment by favonia** [comment]
@iAmSaugata Hi, is there any progress on the issue? The value of `UPDATE_TIMEOUT` would be helpful to diagnose the issue.

**Comment by favonia** [comment]
@iAmSaugata I am closing this with the PR #159 because I seemed to be able to re-create this bug. However, this does not mean your bug has the same cause and please re-open the issue if it's not fixed for you.

**Comment by iAmSaugata** [comment]
Yes, I have tested, no longer getting the error.

**Comment by favonia** [comment]
> Yes, I have tested, no longer getting the error.

Thanks for the confirmation.
