### ISSUE TITLE
Share your use of experimental per-domain proxy settings

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#199]
Are you using the new per-domain proxy settings `PROXIED_DOMAINS` and `NON_PROXIED_DOMAINS`? Please help me come up with a good design by sharing your case. :slightly_smiling_face:

**Comment by EagleonePrimo** [comment]
For me it work fine.

but I think should disable or ignore DOMAINS environment when use PROXIED_DOMAINS or NON_PROXIED_DOMAINS

ps. keep a good work. I like u script it so lightweight and less CPU and memory use

**Comment by favonia** [comment]
Closed in favor of #212.
