### ISSUE TITLE
Accept Go templates for TTL and PROXIED

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#212]
This will provide per-domain settings without using new environment variables.

**Comment by carlox97** [comment]
Hi! Could you please tell me how I can specify per-domain Proxied settings?
I have two domains, I want one to be proxied, but not the other. in docker-compose.yml using commas in proxied doesn't work
Should I run two containers, one for each domain or is there another way?
Thanks

`    environment:
      - CLOUDFLARE_API_TOKEN=xxxxx
        # Your Cloudflare API token
      - DOMAINS=domain1.com,domain2.com
        # Your domains (separated by commas)
      - PROXIED=true, false
        # Tell Cloudflare to cache webpages and hide your IP (optional)`

**Comment by favonia** [comment]
@carlox97 Hi! There's a section in the README, under `Parameters of new DNS records and WAF lists`, that explains the syntax. Could you take a look and let me know what you think? Thanks!

By the way, this is an old issue and the syntax had changed since this issue. I suggest opening a new issue if you have any question. 🙂

**Comment by carlox97** [comment]
@favonia Thanks! I'm sorry but I had no idea I could expand the bullet lists in the readme 😅, everything is clear now!
```
      - DOMAINS=domain1.com, domain2.com
      - PROXIED=is(domain1.com)
```
as per readme works perfectly fine.
