### ISSUE TITLE
No log line matching the '' filter

### ISSUE THREAD

**Issue by ShlomiD83** [favonia/cloudflare-ddns#426]
Hi,
after the update today, I get this error when quiet mode is enabled. (see title)
Running on RPi OS lite 64 bit.

please assist.

**Comment by ShlomiD83** [comment]
I'm using a Raspberry Pi 4, DDNS updater is running inside Docker.

**Comment by favonia** [comment]
@ShlomiD83 The obvious solution to print out some random stuff to make your system happy. I want to print out something that is the most useful. Do you have a preference? It can literally be almost anything.

**Comment by favonia** [comment]
@ShlomiD83 Hi, could you try the `edge` tag to see if the hack works? Feel free to suggest another message to print.
