### ISSUE TITLE
Fine-tune the hack for #426

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#429]
The hack introduced in #427 for fixing #426 was not carefully designed and should be further improved. Currently, with cron enabled, it will print out
```
🔁 Enabled cron schedule for Cloudflare DDNS (v1.9.1-1-blahblah)
```
in the quiet mode. But maybe this is not the best message we can output.

**Comment by ShlomiD83** [comment]
@favonia maybe just a message that indicates "Quiet Mode" is working as it should?

**Comment by favonia** [comment]
> @favonia maybe just a message that indicates "Quiet Mode" is working as it should?

Like this?
```
🔇 Quiet mode enabled
```

**Comment by ShlomiD83** [comment]
@favonia exactly :)

**Comment by favonia** [comment]
@ShlomiD83 I can implement this, but I might not release a new version just for this change. Is that okay?

PS: The tiny issue (for nitpicking) is that the error messages of privilege dropping will come before the quiet mode message, while in reality the quiet mode is determined before dropping the privileges. Anyways, I doubt anyone would notice this...

**Comment by ShlomiD83** [comment]
@favonia it can wait for the next release, thanks for your help.

**Comment by favonia** [comment]
@ShlomiD83 Out of curiosity, are you using portainer?

**Comment by favonia** [comment]
@ShlomiD83 when you have time, please check if the `edge` tag works as expected :slightly_smiling_face:

**Comment by ShlomiD83** [comment]
@favonia 
![image](https://user-images.githubusercontent.com/17053215/225407143-e385e608-e75f-4587-82db-132248e4d2f0.png)
