### ISSUE TITLE
Migration away from Docker Hub?

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#434]
Recent events and discussions indicated that we should not use Docker Hub as the main publishing platform

- [x] https://github.com/docker/hub-feedback/issues/2314

Current plan:
1. Also publish Docker images in another place
2. The image on Docker Hub will print out a warning

**Comment by WaterLemons2k** [comment]
Hello @favonia! I would like to talk about the **Current plan**:

> 1. Also publish Docker images in another place

Just add another `login-action` step to login to another place (e.g. `ghcr.io`)[^1] and add another image tag for the `metadata-action`[^2].

> 2. The image on Docker Hub will print out a warning

To do this, we need to build the Docker Image twice - once with `build-arg` (for Docker Hub), and once without (for `ghcr.io`).

I would like to open a PR for this issue if possible.

Any idea?

[^1]: https://github.com/docker/login-action#github-container-registry
[^2]: https://github.com/docker/metadata-action#images-input

**Comment by favonia** [comment]
> I would like to open a PR for this issue if possible.

@WaterLemons2k Hi, the only reason I have not done this is that I have unusually high workload from my daytime job this spring. If you want to make a PR, go ahead! However, I should warn you that I am quite picky about the quality of this updater so I might ask you to change several things before accepting it. I hope you can understand. The high workload from my daytime job might also slow down my reviewing.

By the way, to be clear, I have not planned to let the Docker Hub image print out a warning yet. My first step would be setting up a perfectly mirrored image. I am still watching how major open-source projects "flee" from Docker Hub, and I would not automatically assume GitHub is more reliable than Docker. :slightly_smiling_face:

Another thing is that, other than `build-arg`, we can also pass the parameter via environment variables, files, or command-line options. This way we don't have to build two different executables. Unfortunately, I don't have the brainpower to think through it now.

**Comment by WaterLemons2k** [comment]
I get it, but there are somethings I need to talk about.

> Another thing is that, other than `build-arg`, we can also pass the parameter via environment variables, files, or command-line options. This way we don't have to build two different executables.

You may have misunderstood my point. No needs to build two different executables. Instead, a function can be created to get the value of an environment variable, for example:
```go
func isDockerHub() bool {
       if os.Getenv("IS_DOCKERHUB") == "1" {
              return true
       }
       return false
}
       
if isDockerHub() {
	// Do something
}
```

And then, add the `build-arg` option when building the image for Docker Hub, like this:
```bash
docker buildx build --build-arg IS_DOCKERHUB=1 --tag cloudflare-ddns .
```

> Unfortunately, I don't have the brainpower to think through it now.

If you are busy, then let's find another time to talk. Thanks!

**Comment by favonia** [comment]
@WaterLemons2k It seems Docker reversed their decision, so maybe I will close this ticket for now. You are still welcome to create a pull request! to have more mirrors. Thank you for your interest. :heart:
