### ISSUE TITLE
 Failed to detect the IPv4 address

### ISSUE THREAD

**Issue by ShlomiD83** [favonia/cloudflare-ddns#486]
😞 Failed to send HTTP(S) request to "https://cloudflare-dns.com/cdn-cgi/trace": context deadline exceeded
😞 Failed to detect the IPv4 address

Hi,
Getting this error when using the recent Edge image.
This doesn't happen with the Latest image.

Please assist.

**Comment by favonia** [comment]
Let me revert the latest change first.

**Comment by ShlomiD83** [comment]
version: "3"
services:
  cloudflare-ddns:
#   image: favonia/cloudflare-ddns:latest
    image: favonia/cloudflare-ddns:edge
    container_name: cloudflare-ddns
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    read_only: true
    network_mode: host
    environment:
      - CF_API_TOKEN=SomeRandomToken
      - DOMAINS=example.com
      - PROXIED=true
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - UPDATE_CRON=@every 5m
      - IP6_PROVIDER=none
      - DETECTION_TIMEOUT=15s
#    - QUIET=TRUE

**Comment by ShlomiD83** [comment]
> @ShlomiD83 Apologies again for my insufficient testing before merging it into the main branch. I will revert the merge soon. On the other hand, may I understand why you are using the `edge` tag? Is there a feature you are waiting for that was not published yet?

It's stayed that way ever since the Quiet Mode message, never changed it back to the latest tag.

**Comment by favonia** [comment]
@ShlomiD83 Thank you. Could you confirm that the current `edge` tag works? If so, maybe we can close this ticket for now. Thank you again for the reporting the bug.

**Comment by ShlomiD83** [comment]
@favonia current edge works as expected.
Issue can be closed.
Thank you for your hard work!

**Comment by favonia** [comment]
@ShlomiD83 I forgot to say that it's recommended to use the `latest` tag (or a fixed version tag) because I'll be experimenting with new code with the `edge` tag. Thanks!

**Comment by ShlomiD83** [comment]
Thank you @favonia .
I've switched back a while ago to the latest tagged image.

**Comment by favonia** [comment]
@ShlomiD83 This is a head-up---recent versions (1.13.0+) will benefit from an update to your configuration, and I am on the [mission to eliminate the old template from this universe.](#835) In case you or anyone is confused by how to update the configuration, here's the tl;dr:

1. Remove `cap_add: ...` completely.
2. Add `user: "1000:1000"` (or other IDs you want to use).
3. Remove `PUID=...` and `PGID=...` (optional, but why not).

For more information, please see the [CHANGELOG](https://github.com/favonia/cloudflare-ddns/blob/main/CHANGELOG.markdown#1130-2024-07-16) and [README](https://github.com/favonia/cloudflare-ddns?tab=readme-ov-file#-step-1-updating-the-compose-file).

PS: the new template works for older versions of the updater as well!

**Comment by ShlomiD83** [comment]
> @ShlomiD83 This is a head-up---recent versions (1.13.0+) will benefit from an update to your configuration, and I am on the [mission to eliminate the old template from this universe.](#835) In case you or anyone is confused by how to update the configuration, here's the tl;dr:
> 
> 1. Remove `cap_add: ...` completely.
> 2. Add `user: "1000:1000"` (or other IDs you want to use).
> 3. Remove `PUID=...` and `PGID=...` (optional, but why not).
> 
> For more information, please see the [CHANGELOG](https://github.com/favonia/cloudflare-ddns/blob/main/CHANGELOG.markdown#1130-2024-07-16) and [README](https://github.com/favonia/cloudflare-ddns?tab=readme-ov-file#-step-1-updating-the-compose-file).
> 
> PS: the new template works for older versions of the updater as well!

Thanks @favonia, I've made the changes.
