### ISSUE TITLE
Add a custom provider

### ISSUE THREAD

**Issue by augustabt** [favonia/cloudflare-ddns#546]
For my use case being able to configure a custom provider would be useful. It would basically be a http provider like ipify, but with the ability to use an env variable to configure any url.

**Comment by favonia** [comment]
@augustabt Thank you for your feedback. Could you possibly provide more detail about why you might want to use a non-Cloudflare server? I'm quite curious.

PS: ipify was still an option but deprecated because the server does not seem to be actively maintained.
PPS: I might have to think about the configuration interface a bit.

**Comment by augustabt** [comment]
@favonia for sure. My specific use case is I am running a kubernetes cluster with the pods subnet exposed to a vpn I can connect to. Since the pod ip address can change I wrote a service that gets all the currently active pods and exposes one of their ip addresses that can then be used for dns. I think a more common use case would be someone who has a specific provider they want to use instead of cloudflare.

**Comment by favonia** [comment]
@augustabt Sorry for the long delay. I am starting to implement this. The current design is to have something like `custom.url:https://...`. Do you have any other suggestion about the input format?

**Comment by favonia** [comment]
@augustabt I can still change the interface before the release of the next version. Please let me know if you think the implementation should be changed. Thank you!

**Comment by Aiakio** [comment]
> @augustabt Sorry for the long delay. I am starting to implement this. The current design is to have something like `url:https://...`. Do you have any suggestion about the input format?

For now, im using:
```
 - IP4_PROVIDER=url:https://api4.ipify.org
 - IP6_PROVIDER=url:https://api6.ipify.org
```
successfully.

I think its alright if documented properly. Altough i would think that a format like this:
```
 - IP4_PROVIDER_URL=https://api4.ipify.org
 - IP6_PROVIDER_URL=https://api6.ipify.org
```
would be a little easier to understand / read.
