### ISSUE TITLE
1.1.1.1 blocked in China

### ISSUE THREAD

**Issue by andylizi** [favonia/cloudflare-ddns#574]
The 443 port on `1.1.1.1` and co. has been recently blocked in mainland China, and `https://1.1.1.1/cdn-cgi/trace` became inaccessible there.

Would you consider adding an option for `https://www.cloudflare.com/cdn-cgi/trace` or other alternative IP services?

Thank you for the great work on this project!

**Comment by favonia** [comment]
@andylizi If you are using the `edge` version (the pre-release version), you can use `url:URL`. See the `README.markdown` and https://github.com/favonia/cloudflare-ddns/issues/568. I hope that helps!

**Comment by favonia** [comment]
@andylizi Hi, are you able to work around the blockage? On the other hand, maybe you could switch to a Chinese company if the Great Firewall was the issue.

**Comment by andylizi** [comment]
Sorry for replying so late! I'm currently outside of China and have been unable to SSH back home for some reason (unrelated to DNS), so I can't test it for now. The solution seems straightforward and there should be no reason it wouldn't work, though.

I personally would still prefer Cloudflare since I trust their stability slightly more than the others😁, but it doesn't really matter in this case, either is just fine.

Thanks again for your help! Feel free to close if you'd like. Or if you want to wait for the actual result, I will get back to you later today, probably.

**Comment by andylizi** [comment]
Unsurprisingly, it worked. 🎉

**Comment by favonia** [comment]
@andylizi Hi, the version with the `url:URL` feature has been officially released as 1.10.0. It is recommended to switch back to the `latest` tag because the `edge` tag was for me to try out experimental features. :sweat_smile:
