### ISSUE TITLE
Support Uptime Kuma

### ISSUE THREAD

**Issue by jschneekloth** [favonia/cloudflare-ddns#599]
This service works much better for me than previous solutions I was using.  Internally to my setup I'm using uptime kuma for monitoring and service health, looks like the healthchecks here are coupled directly to format of healthchecks.io implementation which isn't compatible (at least as far as I can tell) with uptime kuma push monitors.  Example URL of uptime kuma:

http://my_internal_ip:3001/api/push/rW5bnO05uv?status=up&msg=OK&ping=
or
http://my_internal_ip:3001/api/push/rW5bnO05uv

Both work, status, msg and ping are optional.  Would really like the heartbeat checks here to be able to ping uptime kuma as well.

**Comment by favonia** [comment]
@jschneekloth Thanks for the suggestion. I actually implemented a basic client talking to Uptime Kuma before (see #497), but eventually removed it (#512) due to the lack of testing. I will need your help to test that it _really_ works. Is that okay? I should add that the documentation of Uptime Kuma was less detailed than Healthcheck.io; it didn't say, for example, what happens when there's an error. (I know you might be thinking about pinging, but a robust implementation should also check whether the pinging is successful.)

**Comment by favonia** [comment]
@jschneekloth The main incompatibility is that Kuma's push monitor does not support the POST method. See https://github.com/louislam/uptime-kuma/pull/1991.

**Comment by favonia** [comment]
_(Reopening the issue; waiting for confirmation from @jschneekloth)_

**Comment by favonia** [comment]
@jschneekloth Thank you for your confirmation. I will assume the :+1: you made means you have tested that it works. :smiley: Once the next version is released, please revert the `edge` tag back to `latest` tag in your setup. The `edge` tag is for me to test new code, and you probably do not want to use that.

**Comment by favonia** [comment]
@jschneekloth Out of curiosity, you can only see the _first_ success message, right? And I suppose you think it's okay?

**Comment by jschneekloth** [comment]
I have not tested yet, will do this evening.  I'll grab edge, deploy it and play around with the use-cases you specified.  Will give a report as soon as that's done with any expectations or issues that I see...

**Comment by jschneekloth** [comment]
Testing Results, version: v1.10.1-11-gfb2e872

>>> 1. http://my_internal_ip:3001/api/push/rW5bnO05uv?status=up&msg=Ok&ping= works.

I'm seeing an error

```
cloudflare-ddns  |    😡 The Healthchecks URL (redacted) does not look like a valid URL
cloudflare-ddns  |    😡 A valid example is "https://hc-ping.com/01234567-0123-0123-0123-0123456789abc"
```
>>> 2. http://my_internal_ip:3001/api/push/rW5bnO05uv works as well!

Seeing an error with this one as well:
```
cloudflare-ddns  |    🔧 Monitors:
cloudflare-ddns  |       🔸 Healthchecks:            (URL redacted)
cloudflare-ddns  | 😞 Failed to send HTTP(S) request to the "/start" endpoint of Healthchecks: POST http://my-internal-ip:3001/api/push/rW5bnO05uv/start giving up after 1 attempt(s): context deadline exceeded
```

These are same errors I saw before.  Tool was appending /start and didn't like formatting on above.....wondering if I have the correct version instealled?  This is the image tag I'm using (docker compose): `image: favonia/cloudflare-ddns:edge`

**Comment by favonia** [comment]
@jschneekloth Hi, Uptime Kuma has its own setting UPTIMEKUMA.

**Comment by favonia** [comment]
The error message showed a different UI bug though. It seems the URL redaction could be defeated by showing the error messages. I should work on this on a different PR.

**Comment by jschneekloth** [comment]
I see, I'll add this setting next time, thanks!  Let me know when you would like me to retest and I'll take a look.

**Comment by favonia** [comment]
I believe it's ready for you to retest. It seems you were using HEALTHCHECKS but that was not for Uptime Kuma. Using UPTIMEKUMA _should_ work.

**Comment by jschneekloth** [comment]
### Testing Results
#### http://my_internal_ip:3001/api/push/rW5bnO05uv?status=up&msg=Ok&ping=
Docker compose setting: `- UPTIMEKUMA=http://my-internal-site:3001/api/push/rW5bnO05uv?status=up&msg=OK&ping=`
Uptime Kuma got the notification (service went from red to yellow, which is expected).  Logs from cloudflare-ddns show the following, however:


```
On startup:
cloudflare-ddns  |    😦 The Uptime Kuma URL (redacted) uses HTTP; please consider using HTTPS
cloudflare-ddns  |    😡 The Uptime Kuma URL (redacted) contains an unexpected query msg=... and it will not be used
...
After an update check is completes:
cloudflare-ddns  | 😞 Failed to send HTTP(S) request to Uptime Kuma: Get "http://my-internal-site:3001/api/push/rW5bnO05uv?msg=&ping=&status=up": dial tcp some-totally-incorrect-ip:3001: i/o timeout
```


the `some-totally-incorrect-ip` is of a format that is entirely not correct for my subnet, not sure where this IP came from.  If I had to guess, perhaps gateway/dns isn't being resected for dns resolution?

#### http://my_internal_ip:3001/api/push/rW5bnO05uv
Docker compose setting: `- UPTIMEKUMA=http://my-internal-site:3001/api/push/rW5bnO05uv`

```
On startup:
cloudflare-ddns  |    🔧 Monitors:
cloudflare-ddns  |       🔸 Uptime Kuma:             (URL redacted)

After successful update check:
cloudflare-ddns  | 😞 Failed to send HTTP(S) request to Uptime Kuma: Get "http://my-intrnal-site:3001/api/push/rW5bnO05uv?msg=&ping=&status=up": context deadline exceeded
and afte another check:
cloudflare-ddns  | 😞 Failed to send HTTP(S) request to Uptime Kuma: Get "http://my-internal-site:3001/api/push/rW5bnO05uv?msg=&ping=&status=up": dial tcp some-totally-incorrect-ip:3001: i/o timeout
```

Again, similar failure to above, the `some-totally-incorrect-ip` is for a subnet entirely different from my internal network.  Looks like perhaps the URL to uptime kuma.  Kuma's default push URL (the one you copy from the monitor) is of format `http://whatever-ip-or-address-is-setup:3001/api/push/rW5bnO05uv?status=up&msg=OK&ping=`.  Looks like you may be handling this correctly, and appending the msg, status, and ping in both cases above, but preferable to just use the base url without the optional parameters as input.  This should be working from my ad-hoc testing of just calling the URL in different ways.  As far as the health check, however, all the parameters are optional and simply calling http://whatever-ip-or-address-is-setup:3001/api/push/rW5bnO05uv is sufficient from uptime kuma perspective alone.  I don't think kuma needs to capture that the cloudflare update itself was successful or not, just that cloudflare-ddns is up and running which calling without the additional props does.  I'm not sure if there is any UX or ability for kuma to parse and do anything meaningful with the optional props either.  Additionally, in an ideal world this heartbeat would be done at an interval independently of the dns checks (e.g. uptime by default suggests every 60 seconds, but this is configurable within the kuma monitor).

**Comment by favonia** [comment]
Thanks for the testing!!! I thought they would have "Ok" instead of "OK" (all in caps) in their directly copy-pastable URL. I'll double check on that. I also thought you can check the first "msg" message there. Otoh it's easy not to send anything. I should check the i/o timeout later when I come home. Again thanks for your help! 🙏

**Comment by favonia** [comment]
@jschneekloth Now I'm back home!

1. I checked the source code of Uptime Kuma and it is "OK" and will fix that mistake soon. The program is designed to silently eat up expected arguments without making any noise, so it is a _bug_ if you get any warning.
2. According to https://github.com/louislam/uptime-kuma/issues/279#issuecomment-1356352436, the message will be shown, but indeed, I don't feel you could do anything meaningful with the messages.
3. I have difficulties getting my head around why you would end up with a `some-totally-incorrect-ip`... Are you able to update your IP after the error about the Uptime Kuma server? (Did you intend to say something after "Looks like perhaps the URL to uptime kuma"? It seems the sentence is not complete.)
4. I am a bit reluctant to change the heartbeat rate though, because that would introduce another logic of looping with no real benefits. Is that okay? At very least I will update README to clearly document this.

Again, thank you for your time!

**Comment by jschneekloth** [comment]
Yeah the IP thing is strange, I'll do some more testing tomorrow, my subnet starts 10.blah.blah... and this was displaying something like 140.blah.blah...

As far as heartbeat, I think this can be sort of worked around by editing the monitor in Uptime Kuma, but there is an argument to be made for such an approach.  I view this as sort of two entirely separate use cases and therefor underlying timers.  One use-case is, "hey, is this service still running?" (uptime-kuma) and the other being "hey, was my cloudflare check successful?" (kuma, or more likely something else like your current implementation implies).  Right now my cloudflare check is on a 5 minute timer, but given the stability of my IP, that's quite a short time to be checking for updates.  Maybe I only want to check for IP changes daily?  In that case, I for sure would like to know that the service is still running even if it isn't actively working....sort of a fail fast mantra along with clearly defined use-case boundaries.

Having said all that, I'm totally fine keeping as is, I can deal with this from kuma perspective and if/when it becomes a concern, maybe I can submit a PR with the feature :)

**Comment by favonia** [comment]
@jschneekloth I see your use case. If there's an option, I think it should be a global option applying to both Uptime Kuma and Healthchecks. BTW, this tool also supports a "one-shot" mode with `UPDATE_CRON=@disabled`, which might make your PR plan more challenging.

**Comment by favonia** [comment]
@jschneekloth I have updated the client in #605 so that 

1. You should not get any warning with `msg=OK`
2. The message will always be "OK" instead of trying to send more information.
3. README has a reminder that the user should update the heartbeat interval.

**Comment by jschneekloth** [comment]
Success!
```
cloudflare-ddns  | 🔔 Successfully pinged Uptime Kuma
```

You can likely ignore my previous update/testing, this process exposed an issue in my internal networking setup that I have since fixed and it is very likely your original change worked as you expected as well.

**Comment by favonia** [comment]
@jschneekloth Thank you. I will close this issue as fixed.

**Comment by favonia** [comment]
@jschneekloth The version that supports Uptime Kuma has been released. Please switch back to the `latest` tag if you have not. :smiley:

**Comment by JvdMaat** [comment]
> Success!
> 
> ```
> cloudflare-ddns  | 🔔 Successfully pinged Uptime Kuma
> ```

I am missing a step somewhere. I also get the Success message in cloudflare-ddns. However my Uptime Kuma says it is down:
![image](https://github.com/favonia/cloudflare-ddns/assets/90044149/b41767fb-309c-406e-95b5-34cd3749ea34)
(But the Message is OK... Which is the expected response right?)
What am I missing?
I went to the URL (https://uptimekuma.mydomain.com:3002/api/push/TJl<redacted>?status=up&msg=OK&ping=) in a browser, and then UptimeKuma said it was online.:
![image](https://github.com/favonia/cloudflare-ddns/assets/90044149/1ee2727e-696f-4c6a-8e42-8cfda82a297a)
How can I troubleshoot this?

**Comment by jschneekloth** [comment]
In kuma, ensure you're using the push monitor type and update the heartbeat interval to be the same as the update check time in cloudflare-ddns.

**Comment by favonia** [comment]
I guess I can add a hint if UPDATE_CRON is not "@every 5mins" or something like that...

**Comment by JvdMaat** [comment]
Yeah, I think I got that. I do not specify UPDATE_CRON, so it uses the default 5 mins (300 seconds). I set it to 360 in UK just to give it an extra buffer (on top of the retry...)
![image](https://github.com/favonia/cloudflare-ddns/assets/90044149/68919bfe-f6fe-4872-b932-916fb02edbab)

**Comment by favonia** [comment]
The failure to detect IPv6 addresses counts as a failure. What confused me is why Uptime Kuma is keeping the "OK" :thinking:

**Comment by favonia** [comment]
@JvdMaat Actually, would you mind opening a new issue? I tried to repurpose this issue but it still looks a little bit strange. Let's start fresh with a new issue. (@jschneekloth sorry for the noise :sweat_smile:)

**Comment by favonia** [comment]
@JvdMaat The new thread is at #615.

**Comment by favonia** [comment]
@JvdMaat This is a head-up---recent versions (1.13.0+) will benefit from an update to your configuration, and I am on the [mission to eliminate the old template from this universe.](https://github.com/favonia/cloudflare-ddns/issues/835) The environment variables `PUID` and `PGID` will be ignored from now. In case you or anyone is confused by how to update the configuration, here's the tl;dr:

1. Remove `cap_add: ...` completely (though you don't seem to have this).
2. Add `user: "1000:1000"` (or other IDs you want to use).
3. Remove `PUID=...` and `PGID=...` (optional, but why not).

For more information, please see the [CHANGELOG](https://github.com/favonia/cloudflare-ddns/blob/main/CHANGELOG.markdown#1130-2024-07-16) and [README](https://github.com/favonia/cloudflare-ddns?tab=readme-ov-file#-step-1-updating-the-compose-file).

PS: the new template works for older versions of the updater as well!
