### ISSUE TITLE
Graduating `UPDATE_CRON=@once`

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#604]
@bodak I decided to steal some of your idea in https://github.com/favonia/cloudflare-ddns/issues/409. More precisely, I plan to introduce `UPDATE_CRON=@once` and deprecate `UPDATE_CRON=@disabled`. I wonder why I didn't think about this name in our earlier discussion?! 😅 As for the interaction between this and other options, I believe it's best to terminate the program with an error if `UPDATE_ON_START` is false. This should achieve the ease of use while keeping all options independent.

**Comment by favonia** [comment]
@bodak To clarify, I have not implemented the new option, please do not update your configuration yet.

**Comment by bodak** [comment]
This sounds great!
No rush, I am rarely if ever using `latest` images (`image: favonia/cloudflare-ddns:1.10.0`).

**Comment by favonia** [comment]
@bodak The version that accepts the new setting has been released as 1.11.0. :smiley:
