### ISSUE TITLE
Timestamps in log

### ISSUE THREAD

**Issue by chrede88** [favonia/cloudflare-ddns#634]
I really like this great little project. Especially the very small footprint!:)

Now, I would really appreciate a very small addition: Timestamps in the log output.
The logs are great in general, but without timestamps any diagnosis is quite difficult.

**Comment by favonia** [comment]
@chrede88 Thanks for the suggestion! Are you using Docker Compose? If you are using it, the option `--timestamps` of the command `docker compose logs` should show the timestamp. It's for this reason I didn't implement timestamps.

I am also interested in knowing the issues you might have encountered.

**Comment by chrede88** [comment]
I've deployed it in a my Kubernetes cluster. I don't think any formatting is possible. As far as I know any logs posted to Stdout or Stderr are passed along to Kubernetes.

**Comment by favonia** [comment]
For Kubernetes, you can probably use `kubectl logs --timestamps`. Does that work? What I meant is that Docker Compose and Kubernetes are already time-stamping every line, and thus I tried to avoid having two timestamps on the same message.

**Comment by favonia** [comment]
On the other hand, maybe it makes sense to print out the time in the countdown message. I'll have to think about it. Do you have other usage of the timestamps?

**Comment by chrede88** [comment]
Ah yes, I had totally forgot about the --timestamps flag. That's really all I need.

**Comment by favonia** [comment]
The timezone data was compiled into the binary so it should be possible. 😎 On the other hand I will close this issue for now. Still, thanks for the feedback!

**Comment by favonia** [comment]
@chrede88 BTW, I forgot to mention that, maybe the next version will embed [shoutrrr](https://github.com/containrrr/shoutrrr) for notifications, and if that was implemented, I estimated that the compressed Docker image will grow from 2.X to 4.X MB. It's still "small" but the growth is significant given how tiny it is right now. I hope that is okay for you. (If not, please let me know so that I have some motivations to find alternative solutions 😆)

**Comment by p1gd0g** [comment]
How about the binary users? 
@favonia

**Comment by mstrey** [comment]
The time on logs with `docker compose logs --timestamps` are in GMT 0 but i've in my docker-compose.yml the parameter to show in my local time:

```
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}
      - DOMAINS=${DOMAINS}
      - PROXIED=true
      - TZ=America/Sao_Paulo
```
I've also set the time zone files:

```
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
Any tip about how to fix this?
