### ISSUE TITLE
Store CF_API_TOKEN in file.

### ISSUE THREAD

**Issue by NWarila** [favonia/cloudflare-ddns#668]
Would it be possible to add an option to store the CF_API_TOKEN in a file? Generally I version control all of my docker-compose containers in a private github repo and store my sensitive files in an external directory to what I sync. Its a niche situation, but perhaps a configuration others also utilize.

**Comment by favonia** [comment]
In case it's not clear, yes, use `CF_API_TOKEN_FILE`.

**Comment by naanlizard** [comment]
Small issue here, other services (letsencrypt and stuff using it) tend to use cloudflare's API key in the form of 

```
# Cloudflare API token used by Certbot
dns_cloudflare_api_token = 0123456789abcdef0123456789abcdef01234567
```

https://certbot-dns-cloudflare.readthedocs.io/en/stable/

would it be possible to add support for that formatting so I don't need as many files kicking around?

**Comment by favonia** [comment]
@naanlizard Hi, could you possibly start a new issue even though it's somewhat related? Thanks!

**Comment by naanlizard** [comment]
Of course, sorry about that I was being a bit lazy
