### ISSUE TITLE
1.1.1.1 appears to be blocked or hijacked by your ISP or your router

### ISSUE THREAD

**Issue by ShlomiD83** [favonia/cloudflare-ddns#696]
Hi @favonia,
I see alot of these messages on my log
`2024-02-28T06:22:55.183428570Z 😞 1.1.1.1 appears to be blocked or hijacked by your ISP or your router
2024-02-28T06:22:55.191283277Z 😞 1.0.0.1 is not working either---perhaps the network is down; sticking to 1.1.1.1`

1.1.1.1 isn't blocked or hijacked, when my IP changes the container updates Cloudflare succussfully so I don't know why these messages.

can you plesae assist?

**Comment by favonia** [comment]
@ShlomiD83 Thanks for the reporting. By any chance, did you run the container before the network is fully up?

**Comment by ShlomiD83** [comment]
@favonia I'm not realy sure.
I'll keep an eye fot these messages the next time I reboot my Pi.

**Comment by favonia** [comment]
@ShlomiD83 I believe this was what's happening: the tool pings 1.1.1.1 to work around some annoying routers/ISPs which think 1.1.1.1 is a private IP, and the tool discovers that it could not access 1.1.1.1 properly, but as an additional checking, it then pings 1.0.0.1 and discovers that that doesn't work either, concluding that the network is probably (temporarily) down and decided to sticks to 1.1.1.1. This pinging is necessary to work around the (still existing) routers and ISPs out there, and the second pinging successfully discovered that changing the IP to 1.0.0.1 will not help. My guess is that the network has not been properly set up during the pinging (e.g., maybe some network-related services are not up) but it's set up when the tool tried to figure out the public IP. If it's the case, there's no bug or anything you should do, except that maybe I could rework the messages.

**Comment by ShlomiD83** [comment]
@favonia I don't think you should bother, I'll keep an eye for these messages in the future.

**Comment by favonia** [comment]
@ShlomiD83 In case you are wondering how to enforce the initialization order, this might help: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget. The "bad ISP" detection needs fully working IPv4 except the DNS resolver.

**Comment by favonia** [comment]
I updated the messages in hope that they are clearer. Let me know if you have issues other than the network is still being set up when running the tool.

**Comment by ShlomiD83** [comment]
@favonia I need to use the latest or edge?

**Comment by favonia** [comment]
@ShlomiD83 You can and probably should continue using `latest` (the stable version). So far I only changed the messages and no actual functionality was affected. What I meant is that I am not 500% sure if "the network was still being set up (so that the pinging failed" is the only issue we are dealing with here.

**Comment by ShlomiD83** [comment]
@favonia didn't see any errors in the last couple of days, I believe it's a network not being fully up or a router restart.
