### ISSUE TITLE
Subdomain & cloudflare ddns

### ISSUE THREAD

**Issue by leoduth** [favonia/cloudflare-ddns#708]
Hello,

I would like to configure cloudflare-ddns , and I have a machine with about 20 subdomains to configure all on the same IP.

Should I add all the domains as below, or will just *mydomain.fr work for all of them?

docker run \ --network host \ -e CF_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN \ -e DOMAINS=example.org,subdo1.example.io, subdo2.example.io \ -e PROXIED=true \ favonia/cloudflare-ddns 

Thank you in advance and have a nice day  :)

**Comment by favonia** [comment]
`*.mydomain.fr` will not work. The wildcard domain is a separate, "fail-over" domain that is different from other domains. The alternative is to have only a DNS record for the wildcard domain and then let your machine decide what to do.

**Comment by leoduth** [comment]
Thanks for your feedback, so I have to specify in the file all the sub-domains to be updated?

**Comment by favonia** [comment]
> I have to specify in the file all the sub-domains to be updated?

As I said, you could adjust your setup so that there's only one wildcard DNS record, and then your machine does the dispatching. That also gave you the freedom to dynamically add or remove host on your machine.

**Comment by leoduth** [comment]
Ok, it's automatic ? because i use traefik, and i and I would like to make sure that all sub-domains are well updated

**Comment by favonia** [comment]
@leoduth Could you elaborate on what "it" is in your question "it's automatic?" Traefik can work with wildcard DNS records, but it seems you are not completely sure how all of these tools and protocols fit together. This tool does and only does one thing: updating the IP address of the specified DNS records. For configuring Traefik, perhaps you can get more help in places like [their forum](https://community.traefik.io/) and maybe it is helpful to also learn more about [wildcard DNS records](https://en.wikipedia.org/wiki/Wildcard_DNS_record).

**Comment by favonia** [comment]
@leoduth Hi, did you manage to solve the problem? Is the system working and being configured in a way that you are satisfied with?

**Comment by leoduth** [comment]
Hello @favonia Thanks for your follow up! I finally took the easy way out by manually indicating each subdomain, as I couldn't configure otherwise.

Besides, I was wondering how I could add additional domains later on.

I managed the container via portainer

**Comment by favonia** [comment]
You roughly have two choices (or using a mix of these two):

1. Both Cloudflare and this tool uses one wildcard domain instead of that many subdomains.
2. Both Cloudflare and this tool manually lists all domains.

The second one is conceptually easier, and it sounds like what you are using now. The first one requires clear understanding of how DNS wildcard domains work, but could save you some work. **In either case, you need to keep Cloduflare and this tool in sync.**

Should we close this issue, then?

**Comment by favonia** [comment]
I am closing this issue due to lack of responses. @leoduth, please feel free to reopen this. :grin:
