### ISSUE TITLE
Get IP from a specific ethernet interface

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#713]
Inspired by https://github.com/TimothyYe/godns/issues/238: maybe there are still cases where manual specification of the interface makes sense.

**Comment by favonia** [comment]
The Go standard library does not provide an easy way to specify the interface. :upside_down_face:

**Comment by tchar** [comment]
@favonia Hello. I am interested in specifying a custom interface.

What I ended up doing is run `cloudflare-ddns` in a bridged  network and create a small function to get the interface on the host machine. I spinned up a server listening on a docker IP like 172.xx.0.1:9000 and then specify the provider as url like `url:http://172.xx.0.1:9000/ip`

I came across a python version here [https://stackoverflow.com/a/24196955](https://stackoverflow.com/a/24196955). One can use flask to serve. There is also a node version here [https://stackoverflow.com/a/8440736](https://stackoverflow.com/a/8440736) which can be served with something like express.

It is a bit dirty but this should work even with custom commands to get an IP that is not directly related to an interface.

**Comment by favonia** [comment]
> What I ended up doing is run `cloudflare-ddns` in a bridged network and create a small function to get the interface on the host machine. I spinned up a server listening on a docker IP like 172.xx.0.1:9000 and then specify the provider as url like `url:http://172.xx.0.1:9000/ip`

This is way too complicated... you deserve a much better solution!!!

The code you showed will choose the "first" IP in the IP family, while the current `local` provider will check which IP is actually usable for connecting to the internet. Ideally, the implementation will inspect the routing table etc. to find out the path. Ideally, there should be a way to hack the standard library to force the interface while trying to connect to the internet.

**Comment by favonia** [comment]
@tchar Hi, I think more about this and feel the design is a bit unclear to me. So I'd like to just ask you directly: if you specify an interface and it magically has many seemingly valid IP addresses, what do you want the updater to do?

**Comment by tchar** [comment]
Hey @favonia indeed it seems like you would have to compromise, although I'm curious how often does something like this is the case.

One possible solution is to allow the user to select family (ipv4 vs ipv6) and index (0, 1, ...).

Now the family is clear, but the question is: Is it possible for the code to run two consecutive times and give a different order for the IPs?

If the answer is no you could do it like in the following scenario.

Say machine has two IPs on interface eth1:
10.0.0.2 and 10.0.0.3 and some ipv6.

Specifying something like

local:ipv4:eth1/0  would give 10.0.0.2, and
local:ipv4:eth1/1 would give 10.0.0.3
local:ipv4:eth1/2 would give empty
local:eth1/2 would give the ipv6

**Comment by favonia** [comment]
@tchar The ipv4/6 would not be needed because provider is set separately for `IP4/6_PROVIDER` :wink:. BTW, by any change, are you using `url:http://172.xx.0.1:9000/ip` to transfer an **IPv6** address? If so, it might stop working in the upcoming version...

**Comment by tchar** [comment]
> @tchar The ipv4/6 would not be needed because provider is set separately for `IP4/6_PROVIDER` 😉. BTW, by any change, are you using `url:http://172.xx.0.1:9000/ip` to transfer an **IPv6** address? If so, it might stop working in the upcoming version...

@favoniaYes, I am using this, but for **ipv4**, not **ipv6**.

If you would put the correct number to `xx` I would be concerned haha. You nailed the port and almost the path.

**Comment by favonia** [comment]
Well I'm only using the public information you provided in the issue. @tchar

**Comment by favonia** [comment]
@tchar So, at least on Linux, I believe the IP lists came from filtering the output `getifaddrs`, but I don't see any guarantee that its output is deterministic or ordered in a particular way. This means that it's possible that `eth0/0` could change (!).

**Comment by favonia** [comment]
@tchar BTW, for your workaround, I just got a new idea: maybe #935 could make it easier?

**Comment by favonia** [comment]
@tchar Anyway, I wish to learn more about your setup. Are these following statements true?

1. The default routing of `1.1.1.1` on your host **will not** go through the ethernet interface you wish to use. (If it will, then you could just use the current `local` provider.)
2. However, the routing of `1.1.1.1` on your host **after deleting all routing rules using other interfaces** WILL go through the ethernet interface you attempt to specify. (You can get the routing table by running `route -nev` on a Linux box.) I was trying hard to implement something in this direction, but I should have checked with you first.

If the second item is not true in your case, then I think we really have to read the addresses directly from the interface, and there's really no way to tell which address to use when there are multiple addresses. (I didn't even find the guarantee that the addresses will be presented in the same order.) I just checked `ddclient` and it's reading the first address.

**Comment by favonia** [comment]
@tchar Alright, I did some more homework, and have some good and bad news.

- The bad news is that not being able to specify the interface directly is a known weakness of the POSIX socket API. The Go standard library cannot do much here. There's no way to say "use eth0 to connect to 1.1.1.1". (The only exception is IPv6 link-local addresses, but let's ignore them for now.)
- The semi-good news is that even the Linux kernel seems to be choosing the "first" IP address that "makes senses" if existing hints did not sufficiently ping down the address. So, "choosing the first one" is expected. There are many criteria we could use to determine whether an address is "reasonable":
  - Obviously, for IPv4 you ignore IPv6 addresses and vice versa. (However, should IPv4-mapped IPv6 addresses treated as IPv4 ones or just rejected?)
  - Next, we probably want to skip IPv6 link-local addresses because an IPv6 interface would likely have one.
  - Maybe we should also ignore multicast IP addresses and IPv4-mapped IPv6 addresses.

May I have your confirmation that your address will be some global unicast IPv4 address? Also, may I learn more about your network setup, especially why the current automatic selection fails?

**Comment by tchar** [comment]
I am not sure what is considered to be a weird address.

In my case I am using a VPN tunnel for VLAN.

The IPv4 is a valid one, but any service can be accessed only from those in the VPN VLAN network.

I hope this makes more sense.

**Comment by favonia** [comment]
@tchar Thanks. I have three questions:

1. Are your private IPs within the standard range?
   - 10.0.0.0/8
   - 172.16.0.0/12
   - 192.168.0.0/16
2. I suppose using the VPN is the reason why connecting to some public website (e.g., `1.1.1.1`) does not work, right? That is, the current detection code would give you a non-VPN IP.
3. If this is a VPN totally under your control, perhaps you could assign the same IP to your machine every time? (That is, maybe you do not need DDNS at all.)

**Comment by tchar** [comment]
@favonia 

Here is an example of imaginary interfaces to help you understand a bit how the system works.
`eth0`: Normal interface
`tun0`: Interface for VPN
`tun1`: Interface for VPN VLAN
`docker0-xx`: Docker interfaces

1. The IPs I see do not belong in these ranges. I am not sure if they will ever be in these ranges, but I think not since the machine has to be discoverable outside of its private network.
2. The thing is that the machine has a ton of interfaces. Some belong to docker, some belong to VPN tunnels (not the VPN VLAN), and there is one for the VPN VLAN. I am not sure what the local algorithm does, but since I cannot pick an interface, I am using the aforementioned solution. Keep in mind that when the machine wants to connect to the internet, `eth0` or `tun0` may be used, but **not** `tun1`, unless the traffic is intended for one of the other machines in the VPN VLAN.
3. I cannot assign the same IP, and I am not sure it is the best practice to do so. If I could/would, I guess I would not use DDNS at all.

Let me know if you need any other information.

**Comment by favonia** [comment]
@tchar Thank you! Is the (first) IP assigned to `tun1` the IP you want to use to update DNS records? (I am just checking that the algorithm in my mind would work.)

**Comment by tchar** [comment]
Yes, there is only one IPv4 there.

**Comment by favonia** [comment]
@tchar BTW, the [Go code you mentioned earlier](https://gist.github.com/schwarzeni/f25031a3123f895ff3785970921e962c) (which is based on the [code on stackoverflow](https://stackoverflow.com/questions/27410764/dial-with-a-specific-address-interface-golang)) is not correct. It's assuming that the Go standard library always returns something of type `*net.IPNet` for interface addresses. I just checked the source code and it could be `*net.IPAddr` on Darwin, FreeBSD, and Windows. So, yeah, if you try it on Windows I guess it would fail.

**Comment by favonia** [comment]
@tchar You may try out the `specify-iface` branch (PR #941) with the IP provider `local:tun1`. I have two questions for you:

1. Is the syntax `local:tun1` "obvious, stupid, crystal clear without reading the manual" to you?
2. If you have tried out the PR/branch, does it work for you?

**Comment by tchar** [comment]
@favonia I tested it out, and it works. I only had to put it in host mode instead of bridge.

Regarding the syntax, it makes sense no problem. If I were you, I would prefix the interface with something like `if`. For example. `local:if/tun1` [since `/` is an invalid name].(https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/lib/utils.c?id=1f420318bda3cc62156e89e1b56d60cc744b48ad#n827)

You could even have a simple mode (`local:tun1`) and a verbose mode (`local:if/tun1`) in case you want to reserve `local` for something more than interfaces in the future.

Alternatively you could use a different keyword than local (like `interface`).

This is up to you, either works and makes sense.

**Comment by favonia** [comment]
@tchar Wow, that's a great suggestion! I propose using

> `IP6_PROVIDER=local.iface:eth0`

This leverages the existing `cloudflare.doh` and `cloudflare.trace` providers, though I admit the syntax might be a bit confusing: it reads more like `local.(iface:eth0)` instead of the intended `(local.iface):eth0`. I considered alternatives like `local.if:eth0` and `local.interface:eth0`, but `if` might be misunderstood as a condition, and ironically, `interface` feels less clear than the abbreviation `iface` to me.

Once we establish `local.iface`, we could potentially introduce `local.route:host` and rebrand `local` as

> `IP6_PROVIDER=local.route:api.cloudflare.com`

I wonder what you think about these changes? I am making the changes now, but it is easy to adjust the syntax before the release.

**Comment by favonia** [comment]
@tchar I released 1.15.0 with the syntax `local.iface:<iface>`, but clearly documented that the syntax will not be finalized until 1.16.0. We have lots of time to pin down the design. :grin:

**Comment by tchar** [comment]
@favonia That's great. I will pin the version to 1.15.0 so I don't get any surprises for now.

Thanks

**Comment by tchar** [comment]
@favonia As a user, I find these formats identical in usability. As a dev, it's your project; you should decide which design is best for the project's life. You know it inside out.

 Both formats are better than local:<iface> because they are more verbose. Other than that. I am happy.

**Comment by favonia** [comment]
Closing this as there's nothing to do for now.
