### ISSUE TITLE
Add Cloudflare comments to updated records

### ISSUE THREAD

**Issue by pterhaar** [favonia/cloudflare-ddns#715]
Would be cool if we could add text to the Cloudflare comment field for the updated record.
Preferable if the comment can be personalised.

**Comment by favonia** [comment]
@pterhaar Thanks for the suggestion. New DNS records already come with the comment `"Created by cloudflare-ddns"`. I didn't change existing records because I'm worried that there might be existing comments that are significant---in general all parameters of existing records are preserved except the IP address. May I know how these comments would be used?

**Comment by pterhaar** [comment]
The comment is useful in case of inspection of Cloudflare records, for updated records just as for new ones.
I know that I will make mistakes, because I have a Cloudflare account with dozens of domains. Especially with those domains that I don't look at for months at a time.
The comment could be optional and preferably the text could be set by parameter.

**Comment by favonia** [comment]
@pterhaar I need more information to pin down the design: for the domains that should be updated, what might have prevented you from adding comments to them manually? The tool should preserve all comments you put in. I felt this might have solved your problem (and we do not have to worry about comment overwriting).

PS: The technical difficulty of the current Cloudflare API is that it is sometimes tricky to distinguish "emptying the comment" from "keeping the comment" (there's a long revision history and I was personally involved...).

**Comment by favonia** [comment]
BTW, tags might have been more appropriate, but they are not available in free plans. :upside_down_face:

**Comment by favonia** [comment]
@pterhaar Hi, given that the current updater already puts in the comment, I suppose you are requesting a flag to change the default comment. Is that a good summary? Comments in existing records will always be kept and I believe it's better the keep that behavior. If you wish to add comments to existing behaviors, you can just delete them and restart the updater.

**Comment by favonia** [comment]
@pterhaar New proposal: how about making the default as "no comment" and only set the comment for new records when `RECORD_COMMENT` is not empty?

**Comment by pterhaar** [comment]
Cool!

From: favonia ***@***.***>
Date: Saturday, 29 June 2024 at 16:14
To: favonia/cloudflare-ddns ***@***.***>
Cc: Peter ter Haar ***@***.***>, Mention ***@***.***>
Subject: Re: [favonia/cloudflare-ddns] Add Cloudflare comments to updated records (Issue #715)

Closed #715<https://github.com/favonia/cloudflare-ddns/issues/715> as completed via #783<https://github.com/favonia/cloudflare-ddns/pull/783>.

**Comment by favonia** [comment]
@pterhaar Thanks. You can try out `RECORD_COMMENT` with the Docker tag `edge` (development version) before the next release.
