### ISSUE TITLE
Time to update

### ISSUE THREAD

**Issue by taimadoCE** [favonia/cloudflare-ddns#729]
Hi, friends.
How often is the IP verified to correctly redirect the domain/subdomain?

**Comment by favonia** [comment]
@taimadoCE By default, it's 5 mins. See "Schedules, triggers, and timeouts" under [All Settings](https://github.com/favonia/cloudflare-ddns?tab=readme-ov-file#%EF%B8%8F-all-settings).

If there's something I can do to improve the documentation, please let me know! Otherwise I will close this issue.

**Comment by favonia** [comment]
@taimadoCE Is the issue resolved?

**Comment by taimadoCE** [comment]
Oh, sorry. Yes, all ok.

**Comment by favonia** [comment]
@taimadoCE Let me know if you have any suggestions to the documentation.
