### ISSUE TITLE
Accept Cloudflare account names in lieu of account IDs

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#816]
I hate all non-readable magic strings (except for API tokens) :vomiting_face: However, using account names instead of account IDs has two problems:

1. Account names may not unique (or are they?).
2. The token needs the additional Read permission of "Account Settings" to search for an account from its name, which might reveal more information than necessary.

Therefore account IDs should probably still be supported.

UI design: maybe the UI can be the variable `CF_ACCOUNT`?

**Comment by favonia** [comment]
@Gamerou In my original plan, the user only has to provide account names, and the updater should find the account IDs. However now I'm not sure how valuable the lookup feature is, as the user can change the account name at any time. Given that you are likely the first user of the new WAF list updating, I wonder how you feel about this additional feature?

**Comment by Gamerou** [comment]
> @Gamerou In my original plan, the user only has to provide account names, and the updater should find the account IDs. However now I'm not sure how valuable the lookup feature is, as the user can change their account name at any time. Given that you are likely the first user of the new WAF list updating, I wonder how you feel about this additional lookup feature? How much do you want to use account names instead of account IDs?

The lookup feature for account names could be convenient, but since account names can change, it might introduce some instability. Using account IDs directly is more reliable, though slightly less user-friendly.

As a first user, I see value in having the option to use account names for ease of use, especially during setup. However, I would prioritize stability, so if relying on account IDs reduces potential issues, I'm fine with using them instead.

**Comment by favonia** [comment]
@Gamerou Thanks for the comment. Given this, I am thinking about the following format:
```
WAF_LISTS={list1_name}@{account1_id},{list2_name}@{account2_id}
```
Do you have any other preferences? We can use other symbols for `@` but I cannot think of a better one.

**Comment by favonia** [comment]
Let me close this issue and continue the discussion about multiple accounts at #874.
