### ISSUE TITLE
Support updating lists in different accounts

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#874]
Given that the Cloudflare tools are moving away from global account IDs, it's probably better to specify account IDs along with list names anyway. If we do specify account IDs, it's then natural to support lists in different accounts.

**Comment by Gamerou** [comment]
I would opt for the account_id/list_name format. It provides a clear structure that is easy to understand and use.

The list_name@account_id format is also an option, but account_id/list_name seems more intuitive to me and fits better with common practices.

If you opt to allow using just list_name, it could be a nice feature, provided the necessary permissions are granted and there’s a reliable way to ensure that list names are unique or at least easily identifiable.

**Comment by favonia** [comment]
@Gamerou Hi, I just want you to know that, after implementing the Happy Eyeballs algorithm for something unrelated (see #883), 1.14.0 will be released. Once it's released, I will be much more reluctant to change the interface due to backward compatibility. Let me know if you want more time to test it, or I will ship it very soon!

To test the development version, use the `edge` Docker tag.

**Comment by Gamerou** [comment]
> @Gamerou Hi, I just want you to know that, after implementing the Happy Eyeballs algorithm for something unrelated (see #883), 1.14.0 will be released. Once it's released, I will be much more reluctant to change the interface due to backward compatibility. Let me know if you want more time to test it, or I will ship it very soon!
> 
> 
> 
> To test the development version, use the `edge` Docker tag.

Thanks for the heads-up! I'm really excited about the upcoming 1.14.0 release. No need to wait on my end—I’ll find time to upgrade when I can. Go ahead and ship it!
