### ISSUE TITLE
Log date and time?

### ISSUE THREAD

**Issue by mdhwoods** [favonia/cloudflare-ddns#887]
Possible to add date and time to the log so i can see when it last checked? Just a feature request more then anything.

**Comment by favonia** [comment]
@mdhwoods Are you using Docker compose? If so, `docker-compose logs --timestamps` will give you the timestamps. (This is one of the few reasons why it has not been implemented.)

**Comment by mdhwoods** [comment]
Didn’t use compose when building this one. But can. Used portainer. Will use logs —timestamp next time I rebuild the container. On Aug 24, 2024, at 5:46 PM, favonia ***@***.***> wrote:﻿
@mdhwoods Are you using Docker compose? If so, docker-compose logs --timestamps will give you the timestamps. (This is one of the few reasons why it has not been implemented.)

**Comment by favonia** [comment]
@mdhwoods The `--timestamp` option is not for you to build images, but to view the log of an existing container with timestamps. Anyway, if you are using Portainer, a similar option exists. Check out this website and enable "Show timestamp": https://docs.portainer.io/user/docker/containers/logs

**Comment by favonia** [comment]
@mdhwoods If you are happy with the timestamps provided by Portainer, I will close this issue soon (with an update to the FAQ section). If you think the updater should still timestamp the updates despite the existing timestamps, please respond with more comments. Thanks!

**Comment by mdhwoods** [comment]
Ive been in there so many times never even saw that…. Thanks this is fine.On Aug 25, 2024, at 6:46 AM, favonia ***@***.***> wrote:﻿
@mdhwoods If you are happy with the timestamps provided by Portainer, I will close this issue soon (with an update to the FAQ section). If you think the updater should still timestamp the updates despite the existing timestamps, please respond with more comments. Thanks!

**Comment by favonia** [comment]
Closing this. (BTW, perhaps you would like to respond directly on GitHub.)
