### ISSUE TITLE
Proxy status of DNS records was not updated

### ISSUE THREAD

**Issue by crunchingcode** [favonia/cloudflare-ddns#912]
I created record by hand and put in a bogus ip (not proxied) I then added it in to the container to update the ip and had proxied set to true.  While it did update the IP to the correct ip, it did not set it to proxied.

**Comment by favonia** [comment]
Existing record parameters are (almost) always preserved. Please consult the README for details, thanks!

**Comment by favonia** [comment]
I forgot to thank you for the report. This finally motivates me to resolve #840.

**Comment by favonia** [comment]
@crunchingcode Basically the design principle is that your manual inputs (bogus or not) are cherished and the updater only do the bare minimum. Let me know if you have a use case where the updater should actively overwrite attributes.

**Comment by crunchingcode** [comment]
I don't have a use case tbh.  I just so happened to notice lol.  you have a point.
