### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference - Since last update v1.14.1

### ISSUE THREAD

**Issue by ShlomiD83** [favonia/cloudflare-ddns#929]
Hi @favonia ,
after the latest update the container isn't working, please see attached logs.

[cloudflare-ddns_logs.txt](https://github.com/user-attachments/files/16992022/cloudflare-ddns_logs.txt)

version 1.14.0 works fine.

**Comment by q734738781** [comment]
same for me

**Comment by favonia** [comment]
@ShlomiD83 Wow, I see the bug. Will fix it in no time.

**Comment by ShlomiD83** [comment]
> @ShlomiD83 Wow, I see the bug. Will fix it in no time. Thank you for your report!!!

Thanks @favonia

**Comment by favonia** [comment]
@ShlomiD83 @ponfertato Before I release a hotfix, may I have a confirmation from any of you that the `edge` tag (as in `favonia/cloudflare-ddns:edge`) works as expected? The fixed version should print `🌟 Cloudflare DDNS (v1.14.1-N-xxxxxxxx)` for some N >= 1.

Really sorry about such a stupid bug. :facepalm: 

I added more tasks to detect this bug for now, and I will try to find a more fundamental way to prevent this (other than changing to a safer language).

**Comment by ShlomiD83** [comment]
@favonia using the `latest` tag results in the same error, I need to use the `edge` tag?

**Comment by favonia** [comment]
> @favonia using the `latest` tag results in the same error, I need to use the `edge` tag?

That's correct, because I have not released it. (The `lastest` tag refers to the lastest _released_ one.)

**Comment by ShlomiD83** [comment]
> > @favonia using the `latest` tag results in the same error, I need to use the `edge` tag?
> 
> That's correct, because I have not released it. (The `lastest` tag refers to the lastest _released_ one.)

the `edge` version is working as expected.

`🌟 Cloudflare DDNS (v1.14.1-1-g3ea0eb9)`

**Comment by nixielectra** [comment]
yup, edge working find

![image](https://github.com/user-attachments/assets/a15cf176-02b9-4d50-9935-03772cca27b2)

**Comment by ponfertato** [comment]
Just checked, the `edge` tag is working properly, thanks for the quick fix!
![изображение](https://github.com/user-attachments/assets/130cb365-f282-47bd-9fee-535652c122a9)
