### ISSUE TITLE
Failed to check the existence of a zone named

### ISSUE THREAD

**Issue by s1s1fo** [favonia/cloudflare-ddns#977]
When  migrating to a new server but keeping the same domain and cloudflare settings, I'm getting:
Failed to check the existence of a zone named mydomain.com
And if I click the url generated I get:

{"success":false,"errors":[{"code":9106,"message":"Missing X-Auth-Email header"},{"code":9107,"message":"Missing X-Auth-Key header"}],"messages":[],"result":null}

Thanks

**Comment by favonia** [comment]
@s1s1fo Thanks for the reporting. The API URL is not to be opened in a browser. The error message you saw is that the Cloudflare server complains the lack of authorization. It thus does not show the essential error that led to the failure of finding your DNS zone.

May I see the log (with the quite mode being disabled, if you are using it) after removing all the private information such as your API tokens and domain names?

**Comment by s1s1fo** [comment]
Thanks for the support.
This is the only log I get with QUIET: false:

🌟 Cloudflare DDNS (v1.15.0-0-g864be42)
📖 Reading settings . . .
   🔸 Use default IP4_PROVIDER=cloudflare.trace
   🔸 Use default UPDATE_CRON=@every 5m
   🔸 Use default UPDATE_ON_START=true
   🔸 Use default CACHE_EXPIRATION=6h0m0s
   🔸 Use default TTL=1
   🔸 Use default DETECTION_TIMEOUT=5s
📖 Checking settings . . .
📖 Current settings:
   🔧 Domains, IP providers, and WAF lists:
      🔸 IPv4-enabled domains:    mydomain.com
      🔸 IPv4 provider:           cloudflare.trace
      🔸 WAF lists:               (none)
   🔧 Scheduling:
      🔸 Timezone:                Europe/Madrid (currently UTC+01)
      🔸 Update schedule:         @every 5m
      🔸 Update on start?         true
      🔸 Delete on stop?          false
      🔸 Cache expiration:        6h0m0s
   🔧 Parameters of new DNS records and WAF lists:
      🔸 TTL:                     1 (auto)
      🔸 Proxied domains:         mydomain.com
      🔸 Unproxied domains:       (none)
      🔸 DNS record comment:      (empty)
      🔸 WAF list description:    (empty)
   🔧 Timeouts:
      🔸 IP detection:            5s
      🔸 Record/list updating:    2m0s

🌐 Detected the IPv4 address xxx.xxx.xxx.xxx
😞 Failed to check the existence of a zone named mydomain.com: HTTP request failed: Get "https://api.cloudflare.com/client/v4/zones?name=mydomain.com&per_page=50": dial tcp: lookup api.cloudflare.com on 127.0.0.11:53: read udp 127.0.0.1:56423->127.0.0.11:53: i/o timeout
⏰ Checking the IP addresses in about 4m13s . . .

**Comment by favonia** [comment]
@s1s1fo It seems your server or your Docker does not have a working DNS. First, could you try this outside the Docker?
```sh
curl https://api.cloudflare.com/client/v4/user/tokens/verify \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer XXXXXXXXXXXX(YOUR-TOKEN)'
```
If it works, and if you are using Docker, could you run some generic image (for example `alpine`) and run the same command? For example, you can start a Docker container
```
docker run -it --rm alpine /bin/sh
```
and then execute
```
apk add curl
curl https://api.cloudflare.com/client/v4/user/tokens/verify \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer XXXXXXXXXXXX(YOUR-TOKEN)'

```

**Comment by s1s1fo** [comment]
I get success code both from the host machine and from a container running on the machine:
{"result":{"id":"xxxxxxxxxxx","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}root@radarr:/#

**Comment by favonia** [comment]
@s1s1fo How did you start the container on your new server? Are you using Docker Compose to start the container?

If you are using Docker Compose, what if you starts the container directly?
```
docker run \
  --network host \
  -e CLOUDFLARE_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN \
  -e DOMAINS=... \
  -e PROXIED=true \
  favonia/cloudflare-ddns:latest
```

If it works, you can try running the Go code directly, bypassing Docker entirely. (This requires the Go installation)
```
CLOUDFLARE_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN \
  DOMAINS=... \
  PROXIED=true \
  go run github.com/favonia/cloudflare-ddns/cmd/ddns@latest
```

The bottom line is that the updater somehow cannot reach your DNS server, and thus cannot resolve `api.cloudflare.com` to an IP address for connection. The testing so far uses Docker but not Docker Compose, so it's very possible that your Docker Compose configuration is the culprit if you are using it.

**Comment by favonia** [comment]
If all of the above works, it means the updater is working as expected and it's likely that something in your Docker Compose configuration messed up the DNS resolution. It will also be helpful to check whether this is the only failing service if you have multiple services in your Docker Compose file. Unfortunately, without further information, it's impossible to know what might be causing the failure of resolving domain names.

**Comment by s1s1fo** [comment]
Thanks, do you see something in my compose? The rest of containers are working ok and no DNS problems being reported:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns
    environment:
      CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
      DOMAINS: $DOMAIN_BASE_NAME
      UPDATE_TIMEOUT: 30s
      PROXIED: true
      RRTYPE: A
      DELETE_ON_STOP: false
      IP6_PROVIDER: none
      QUIET: false

**Comment by favonia** [comment]
@s1s1fo This part of Docker Compose seems to be fine, though `hostname: cloudflare-ddns` and `RRTYPE: A` are not needed. I assume that everything works outside Docker Compose. If that's the case, I'm very confident that your Docker Compose is somehow misconfigured. The fact that other containers do not report errors does not immediately mean the DNS is working---it's possible that the other containers do not need to connect to external servers.

One possible next step is to connect to a container Docker Compose creates and test the networking inside it. For example, you can run
```
docker container ls
```
to find a container that (1) was created by Docker Compose and (2) has enough tools for you to debug the networking. (The `cloudflare-ddns` is minimum and does not contain such tools.) And then you can things like this to test connectivity:
```
docker exec -it <container> /bin/ping api.cloudflare.com
```

**Comment by s1s1fo** [comment]
I can ping succesfully from other containers (tested three). I can't access cloudflare-ddns to make tests from within :-(

**Comment by s1s1fo** [comment]
Thanks anyway. I'll inform if I solve it.

**Comment by favonia** [comment]
@s1s1fo You can also try older versions to see whether the Go runtime has changed. (However, versions before 1.15.0 is taking `CF_API_TOKEN`, not `CLOUDFLARE_API_TOKEN`.) I'm mentioning this because it seems some older version once worked for you.

**Comment by favonia** [comment]
@s1s1fo If you can access the Internet after doing all the steps I laid out above, please let me know---it means there's a bug that I must fix.

**Comment by favonia** [comment]
@s1s1fo Update: to help you debug, now there's a new Docker tag, `edge-debug`, should allow you to ping `api.cloudflare.com` from within without the complicated building steps. Could you try it out? Basically, you replace `latest` with `edge-debug` and redo the pinging you did with other containers.

If you can ping the Cloudflare server, there's an unknown bug in the current updater that I will have to fix. Therefore I'm very interested in learning your discovery. Thank you!

**Comment by favonia** [comment]
@s1s1fo FYI: I will be removing the `edge-debug` tag soon. Please switch back to the stable version `latest` if you have not. Thank you!
