### ISSUE TITLE
Not sure how to make config.

### ISSUE THREAD

**Issue by StefCoders** [favonia/cloudflare-ddns#984]
I have two domains.

panel.xxx.com
live.xxx.com

i want to make panel PROXIED and live UNPROXIED but the readme is unclear. 

I'm not sure how to do this, please help and thanks.

**Comment by StefCoders** [comment]
Nevermind, I asked ChatGPT and it fixed it out.

**Comment by favonia** [comment]
@StefCoders Glad that you figured it out. You can also use `is(panel.xxx.com)` if `live.xx.com` and `panel.xxx.com` are the only two domain names you use.
