### ISSUE TITLE
Records with same name

### ISSUE THREAD

**Issue by vk2r** [favonia/cloudflare-ddns#990]
I've migrated cloudflare-ddns from timothyjmiller to this one and I've encountered the following problem:  

😞 Failed to add a new A record of data.domain.net: A CNAME record with that host already exists. For more details, refer to <https://developers.cloudflare.com/dns/manage-dns-records/troubleshooting/records-with-same-name/>. (81054)

I've disabled IPv6 and tried leaving the configuration as it was before, but I keep getting this message.

Has anyone else experienced this?

**Comment by favonia** [comment]
@vk2r Hi, do you have a CNAME for `data.domain.net`? You need either a CNAME record (as an alias of anther domain) or this tool to update the A record, but not both. You cannot have an A record _and_ a CNAME record. You can check your current configuration in the Cloudflare dashboard.
