### ISSUE TITLE
Is there a possibility to unproxy certain domains?

### ISSUE THREAD

**Issue by zdraganov** [favonia/cloudflare-ddns#995]
From the output of the docker container I see the following message:
```
cloudflare-ddns      |       🔸 Proxied domains:         helloworld.example.com, example.com
cloudflare-ddns      |       🔸 Unproxied domains:       (none)
```
It gives me the feeling that there is option to specify `Unproxied domains` somehow, but it's not clearly documented.
Is there indeed such an option?

**Comment by favonia** [comment]
@zdraganov Yes, it does. I recommend checking the documentation for "🐣 Parameters of new DNS records and WAF lists (proxy status, TTL, and comments)". If you've already looked there, could you please let me know what we could do to improve the documentation? Or, which specific part of the documentation were you referring to when you said it wasn't clear?

**Comment by zdraganov** [comment]
Yeah, it's clear. Closing.
